configfile: "config/config.yaml"

arg1 = config['input_file_name']
arg2 = config['output_file_name']

rule all:
    input:
        expand('{arg1}.txt',arg1=arg1)
    output:
        expand('{arg2}.txt',arg2=arg2)
    shell: 
        "ls -a /source"
