configfile: "config/config.yaml"

in=config['input_file_name']
out=config['output_file_name']

rule all:
    input:
        expand('{in}.txt',in=in)
    output:
        expand('{out}.txt',out=out)
    shell:
        "wc -w {input} > {output}"
